Update README.md to include self-signed certificates information for OIDC
Artifactory uses the GitHub Actions' built-in HTTP client to download the JFrog CLI and perform authentication with JFrog Access for OpenID Connect (OIDC). 

When an Artifactory instance is using self-signed certificates, you may run into the following error: 

Error: Exchanging JSON web token with an access token failed: self-signed certificate in certificate chain

This error occur can occur when trying to download the jfrog cli or exchange a token for OIDC.

To resolve this we need to add the certificates to the NODE_EXTRA_CA_CERTS environmental variable.

- Added a section explaining the use of self-signed certificates with OIDC/Github actions.
- Provided guidance on how to configure self-signed certificates in the context of OIDC.